name: base
channels:
- defaults
- conda-forge
dependencies:
- jupyter_nbextensions_configurator
- jupyter_contrib_nbextensions
- jupyterlab_latex
- nodejs
- notebook=5.6.0
- nb_conda
- jupyterlab-git
- six=1.11.0
- autopep8
- pep8=1.7.1
- nbdime