name: env_gcp_dl_2_0_nightly_27
channels:
- defaults
- conda-forge
dependencies:
- python=2.7
- numpy=1.14.5
- scipy=1.1.0
- scikit-learn=0.20.1
- pandas=0.24.2
- matplotlib
- nomkl # Only for Mac user
- watermark
- pytest=3.6.2
- autopep8
- pylint
- pep8=1.7.1
- pylama=7.4.3
- nbdime
- google-auth
- pillow
- scikit-image=0.14.0
- seaborn=0.9.0
- lime
- google-cloud-storage
- google-cloud-bigquery
- psutil
- pip=19.1
- pip:
  - tfds-nightly==1.0.2.dev201906180105 #1.0.2.dev201906140105
  #- csiphash
  #- siphashc
  #- siphash
  - tf-nightly-2.0-preview==2.0.0.dev20190618 #2.0.0.dev20190614
  #- tf-estimator-nightly==1.14.0.dev2019051601