channels:
- defaults
- conda-forge
dependencies:
- python=3.6.6
- numpy=1.14.5
- scipy=1.1.0
- scikit-learn=0.20.1
- tornado=4.5.3
- jupyter=1.0.0
- jupyterlab=0.34.9
- jupyter_contrib_nbextensions=0.5.0
- jupyter_nbextensions_configurator=0.4.0
- pandas=0.24.2
- matplotlib
- nomkl # Only for Mac user
- notebook=5.6.0
- ipykernel=4.10.0
- ipywidgets=7.4.1
- nbconvert=5.4.0
- watermark
- pytest=3.6.2
- autopep8
- pylint
- pep8=1.7.1
- pylama=7.4.3
- nbdime
- google-auth
- pillow
- scikit-image=0.14.0
- seaborn=0.9.0
- lime
- google-cloud-storage
- google-cloud-bigquery
- psutil
- pip=19.1
- pip:
  - tfds-nightly==1.0.2.dev201905210105
  - tf-nightly-2.0-preview==2.0.0.dev20190521
  #- tf-estimator-nightly==1.14.0.dev2019051601
  #- tfds-nightly==1.0.2.dev201905090105
  #- tf-nightly-2.0-preview==2.0.0.dev20190509
  #- tf-estimator-nightly==1.14.0.dev2019051601
  #- tfds-nightly==1.0.2.dev201904260105
  #- tf-nightly-2.0-preview==2.0.0.dev20190426
  #- tensorflow==2.0.0-alpha0
  #- tensorflow-datasets

